{
 "title": "GR Daniel",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "Percona",
  "MySQL",
  "Group Replication"
 ],
 "time": { "from": "2018-10-25T22:42:20.132Z", "to": "2018-10-26T01:47:55.118Z" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Group Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$host - Channel Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_members_MEMBER_PORT{MEMBER_HOST=\"$host\"}"
    }
   ]
  },
  {
   "title": "Node Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_IN_QUEUE{instance=\"$host\"}",
     "legendFormat": "Transactions in Queue $host"
    }
   ]
  },
  {
   "title": "Node Conflicts (Flow Control)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_CONFLICTS_DETECTED{instance=\"$host\"}",
     "legendFormat": "Conflicts Detected $host"
    }
   ]
  }
 ]
}