{
 "title": "Group Replication",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Group Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Member Statistics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_CHECKED{instance=\"$host\"}",
     "legendFormat": "Tx Checked"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_CONFLICTS_DETECTED{instance=\"$host\"}",
     "legendFormat": "Conflicts Detected"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_IN_QUEUE{instance=\"$host\"}",
     "legendFormat": "Tx In Queue"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_LOCAL_PROPOSED{instance=\"$host\"}",
     "legendFormat": "Tx Local Porposed"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_LOCAL_ROLLBACK{instance=\"$host\"}",
     "legendFormat": "Tx Local Rollback"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_REMOTE_APPLIED{instance=\"$host\"}",
     "legendFormat": "Tx Remote Applied"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_REMOTE_IN_APPLIER_QUEUE{instance=\"$host\"}",
     "legendFormat": "Tx Remote in Applier Queue"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_ROWS_VALIDATING{instance=\"$host\"}",
     "legendFormat": "Tx Rows Validating"
    }
   ]
  },
  {
   "title": "Member Statistics",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "Bps", "label": "bits out (-) / bits in (+)" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_CHECKED{instance=\"$host\"}",
     "legendFormat": "Tx Checked"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_CONFLICTS_DETECTED{instance=\"$host\"}",
     "legendFormat": "Conflicts Detected"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_IN_QUEUE{instance=\"$host\"}",
     "legendFormat": "Tx In Queue"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_LOCAL_PROPOSED{instance=\"$host\"}",
     "legendFormat": "Tx Local Porposed"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_LOCAL_ROLLBACK{instance=\"$host\"}",
     "legendFormat": "Tx Local Rollback"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_REMOTE_APPLIED{instance=\"$host\"}",
     "legendFormat": "Tx Remote Applied"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_REMOTE_IN_APPLIER_QUEUE{instance=\"$host\"}",
     "legendFormat": "Tx Remote in Applier Queue"
    },
    {
     "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_ROWS_VALIDATING{instance=\"$host\"}",
     "legendFormat": "Tx Rows Validating"
    }
   ]
  },
  {
   "title": "$host - Channel Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 13 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_STATUS{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Channel Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_STATUS{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 15 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Applier State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 17 },
   "repeat": "host",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "$host - Applier State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
    }
   ]
  }
 ]
}