{
 "title": "Mosaic KPIs MockUp - v1",
 "description": "Dashboard to view multiple servers",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_up, instance) "
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 }, "content": "$host" },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "GR Applier State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{instance=\"$host\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "Percentage of allocated memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal{instance=\"$host\"} - node_memory_MemFree{instance=\"$host\"} - node_memory_Cached{instance=\"$host\"}) / node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Connections utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(mysql_global_status_threads_connected{instance=\"$host\"} / mysql_global_variables_max_connections{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Queries Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_queries{instance=\"$host\"}[1m]) / 10000"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*mysql_global_status_slow_queries{instance=\"$host\"}/mysql_global_status_queries{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "InnoDB reads on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"}[5m])/rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Read/Writes on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " (rate(node_disk_reads_completed{instance=\"$host\",device=\"sdb\"}[5m]) + rate(node_disk_writes_completed{instance=\"$host\",device=\"sdb\"}[5m]))/20000"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "pmm-singlestat-panel",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
    }
   ]
  },
  {
   "title": "GR Role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 }, "content": "$host" },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "GR Applier State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{instance=\"$host\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "Percentage of allocated memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal{instance=\"$host\"} - node_memory_MemFree{instance=\"$host\"} - node_memory_Cached{instance=\"$host\"}) / node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Connections utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 6 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(mysql_global_status_threads_connected{instance=\"$host\"} / mysql_global_variables_max_connections{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Queries Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_queries{instance=\"$host\"}[1m]) / 10000"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*mysql_global_status_slow_queries{instance=\"$host\"}/mysql_global_status_queries{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "InnoDB reads on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"}[5m])/rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Read/Writes on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " (rate(node_disk_reads_completed{instance=\"$host\",device=\"sdb\"}[5m]) + rate(node_disk_writes_completed{instance=\"$host\",device=\"sdb\"}[5m]))/20000"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "pmm-singlestat-panel",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
    }
   ]
  },
  {
   "title": "GR Role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 8 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 }, "content": "$host" },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 11 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "GR Applier State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 11 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{instance=\"$host\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "Percentage of allocated memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal{instance=\"$host\"} - node_memory_MemFree{instance=\"$host\"} - node_memory_Cached{instance=\"$host\"}) / node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Connections utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 11 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(mysql_global_status_threads_connected{instance=\"$host\"} / mysql_global_variables_max_connections{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Queries Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_queries{instance=\"$host\"}[1m]) / 10000"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*mysql_global_status_slow_queries{instance=\"$host\"}/mysql_global_status_queries{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "InnoDB reads on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"}[5m])/rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Read/Writes on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " (rate(node_disk_reads_completed{instance=\"$host\",device=\"sdb\"}[5m]) + rate(node_disk_writes_completed{instance=\"$host\",device=\"sdb\"}[5m]))/20000"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "pmm-singlestat-panel",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 13 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
    }
   ]
  },
  {
   "title": "GR Role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 13 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 }, "content": "$host" },
  {
   "title": "MySQL Uptime",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 16 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "GR Applier State",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 16 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 16 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{instance=\"$host\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "singlestat",
   "description": "Percentage of allocated memory",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal{instance=\"$host\"} - node_memory_MemFree{instance=\"$host\"} - node_memory_Cached{instance=\"$host\"}) / node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Connections utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 16 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*(mysql_global_status_threads_connected{instance=\"$host\"} / mysql_global_variables_max_connections{instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "Queries Utilization",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_queries{instance=\"$host\"}[1m]) / 10000"
    }
   ]
  },
  {
   "title": "Slow Queries",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*mysql_global_status_slow_queries{instance=\"$host\"}/mysql_global_status_queries{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "InnoDB reads on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100*rate(mysql_global_status_innodb_buffer_pool_reads{instance=\"$host\"}[5m])/rate(mysql_global_status_innodb_buffer_pool_read_requests{instance=\"$host\"}[5m])"
    }
   ]
  },
  {
   "title": "Read/Writes on disk",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " (rate(node_disk_reads_completed{instance=\"$host\",device=\"sdb\"}[5m]) + rate(node_disk_writes_completed{instance=\"$host\",device=\"sdb\"}[5m]))/20000"
    }
   ]
  },
  {
   "title": "Min Space Available",
   "type": "pmm-singlestat-panel",
   "description": "Lowest percent of the disk space available",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
    }
   ]
  },
  {
   "title": "GR Role",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
    }
   ]
  },
  {
   "title": "Threads Connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 18 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])"
    }
   ]
  },
  {
   "title": "Sparklines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Load Average",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 6 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg_over_time(node_load1{instance=\"$host\"}[$interval]) or avg_over_time(node_load1{instance=\"$host\"}[5m])"
      }
     ]
    },
    {
     "title": "CPU Busy",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
     "repeat": "host",
     "format": "percent",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "clamp_max(avg by (instance) \n(sum by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or\n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\nsum by () (\navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\",mode!=\"idle\", mode!=\"total\",job=\"rds-enhanced\"}[5m]))"
      }
     ]
    },
    {
     "title": "RAM Avail",
     "type": "pmm-singlestat-panel",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 10 },
     "repeat": "host",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / \nnode_memory_MemTotal{instance=~\"$host\"} * 100"
      }
     ]
    },
    {
     "title": "Min Space Available",
     "type": "pmm-singlestat-panel",
     "description": "Lowest percent of the disk space available",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
     "repeat": "host",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "min(node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"}/node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs|shm|overlay\"})*100"
      }
     ]
    },
    {
     "title": "Read Disk IOPS",
     "type": "pmm-singlestat-panel",
     "description": "**Max Connections Allowed**",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
     "repeat": "host",
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(node_disk_reads_completed{instance=~'$host',device=~'sdb'}[$interval])"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
     "repeat": "host",
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum by () (rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m])) * 1024"
      }
     ]
    },
    {
     "title": "Data Disk Write IOPS",
     "type": "pmm-singlestat-panel",
     "description": "**Max Connections Allowed**",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 19 },
     "repeat": "host",
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(node_disk_writes_completed{instance=~'$host',device=~'sdb'}[$interval]) or irate(node_disk_reads_completed{instance=~'$host',device=~'sdb'}[5m])"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
     "repeat": "host",
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum by () (rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m])) * 1024"
      }
     ]
    },
    {
     "title": "$host - MySQL Uptime",
     "type": "singlestat",
     "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
     "repeat": "host",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_status_uptime{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Channel Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 25 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_group_members_STATUS{MEMBER_HOST=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Applier State",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 27 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Role",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
      }
     ]
    },
    {
     "title": "Buffer Pool Size of Total RAM",
     "type": "pmm-singlestat-panel",
     "description": "**InnoDB Buffer Pool Size % of Total RAM**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "repeat": "host",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"} * 100) / on (instance) node_memory_MemTotal{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "Peak Questions/Queries per Second (QPS)",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 33 },
     "repeat": "host",
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "sum by () (rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or (sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[$interval])) or sum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[5m])))"
      }
     ]
    },
    {
     "title": "Peak Threads Running",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
     "repeat": "host",
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval])"
      }
     ]
    },
    {
     "title": "Peak Threads Connected",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 37 },
     "repeat": "host",
     "format": "short",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])"
      }
     ]
    },
    {
     "title": "Max DB Conn Allowed",
     "type": "pmm-singlestat-panel",
     "description": "**Max Connections Allowed**",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
     "repeat": "host",
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_max_connections{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "Peak DB Conn Utilization",
     "type": "pmm-singlestat-panel",
     "description": "**% of Connections Used**",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
     "repeat": "host",
     "format": "percent",
     "valueName": "max",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "((mysql_global_status_threads_connected{instance=\"$host\"})/ on (instance) mysql_global_variables_max_connections{instance=\"$host\"}) * 100"
      }
     ]
    }
   ]
  },
  {
   "title": "Multi Instance Graphs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads Created",
     "type": "graph",
     "description": "**Load Average**\n\nOn Linux, this is the number of processes which are in “running” state or in “uninterruptible sleep” state which typically corresponds to disk IO. You can also map LoadAvg to VMSTAT output – it is something like moving average of sum of “r” and “b” columns from VMSTAT.\n\nThis chart is best used for trends. If you notice the load average rising, it may be due to innefficient queries. In that case, it is a good idea to look at PMM's Query Analytics.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mysql_global_status_threads_created{instance=~\"$host\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Threads Running",
     "type": "graph",
     "description": "**Load Average**\n\nOn Linux, this is the number of processes which are in “running” state or in “uninterruptible sleep” state which typically corresponds to disk IO. You can also map LoadAvg to VMSTAT output – it is something like moving average of sum of “r” and “b” columns from VMSTAT.\n\nThis chart is best used for trends. If you notice the load average rising, it may be due to innefficient queries. In that case, it is a good idea to look at PMM's Query Analytics.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "mysql_global_status_threads_running{instance=~\"$host\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Threads Connected",
     "type": "graph",
     "description": "**Load Average**\n\nOn Linux, this is the number of processes which are in “running” state or in “uninterruptible sleep” state which typically corresponds to disk IO. You can also map LoadAvg to VMSTAT output – it is something like moving average of sum of “r” and “b” columns from VMSTAT.\n\nThis chart is best used for trends. If you notice the load average rising, it may be due to innefficient queries. In that case, it is a good idea to look at PMM's Query Analytics.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "MySQL Queries",
     "type": "graph",
     "description": "**MySQL Queries**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the average number of statements executed by the server. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count COM_PING or COM_STATISTICS commands.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$host\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "MySQL Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_connections{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_connections{instance=~\"$host\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "graph",
     "description": "**Load Average**\n\nOn Linux, this is the number of processes which are in “running” state or in “uninterruptible sleep” state which typically corresponds to disk IO. You can also map LoadAvg to VMSTAT output – it is something like moving average of sum of “r” and “b” columns from VMSTAT.\n\nThis chart is best used for trends. If you notice the load average rising, it may be due to innefficient queries. In that case, it is a good idea to look at PMM's Query Analytics.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "node_load1{instance=~\"$host\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "100 - 100 * (node_memory_MemAvailable{instance=~\"$host\"} or (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / (node_memory_MemTotal{instance=~\"$host\"} + 0.1)",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "MySQL Traffic",
     "type": "graph",
     "description": "**MySQL Traffic**\n\nNetwork traffic used by the MySQL process.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(rate(mysql_global_status_bytes_received{instance=~\"$host\"}[$interval]) + rate(mysql_global_status_bytes_sent{instance=~\"$host\"}[$interval])) or (irate(mysql_global_status_bytes_received{instance=~\"$host\"}[5m]) + irate(mysql_global_status_bytes_sent{instance=~\"$host\"}[5m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System - Kernel, Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - System Uptime",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
     "repeat": "host",
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_time{instance=\"$host\"} - node_boot_time{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - System Info",
     "type": "table",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
     "repeat": "host",
     "targets": [
      {
       "expr": "node_uname_info{instance=~\"$host\"}"
      }
     ]
    },
    {
     "title": "Virtual CPUs",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(node_cpu{instance=~\"$host\",mode=\"user\"} or rdsosmetrics_General_numVCPUs{instance=~\"$host\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL - Questions, Connections, Commands, Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "InnoDB Buffer Pool Size",
     "type": "singlestat",
     "description": "**InnoDB Buffer Pool Size**\n\nInnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.  Knowing how the InnoDB buffer pool works, and taking advantage of it to keep frequently accessed data in memory, is one of the most important aspects of MySQL tuning. The goal is to keep the working set in memory. In most cases, this should be between 60%-90% of available memory on a dedicated database host, but depends on many factors.",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 },
     "repeat": "host",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_global_variables_innodb_buffer_pool_size{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Total Database Size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_info_schema_table_size{instance=\"$host\", component!=\"data_free\"})",
       "legendFormat": "Data + Index Size"
      },
      {
       "calculatedInterval": "2m",
       "expr": "sum(mysql_info_schema_table_size{instance=\"$host\", component=\"data_free\"})",
       "legendFormat": "Freeable Size"
      }
     ]
    },
    {
     "title": "$host - MySQL Questions",
     "type": "graph",
     "description": "**MySQL Questions**\n\nThe number of statements executed by the server. This includes only statements sent to the server by clients and not statements executed within stored programs, unlike the Queries used in the QPS calculation. \n\nThis variable does not count the following commands:\n* ``COM_PING``\n* ``COM_STATISTICS``\n* ``COM_STMT_PREPARE``\n* ``COM_STMT_CLOSE``\n* ``COM_STMT_RESET``",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_questions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_questions{instance=\"$host\"}[5m])",
       "legendFormat": "Questions"
      }
     ]
    },
    {
     "title": "$host - MySQL Connections",
     "type": "graph",
     "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval])  or mysql_global_status_threads_connected{instance=\"$host\"} )",
       "legendFormat": "Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_max_used_connections{instance=\"$host\"}",
       "legendFormat": "Max Used Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_max_connections{instance=\"$host\"}",
       "legendFormat": "Max Connections"
      }
     ]
    },
    {
     "title": "$host - Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, rate(mysql_global_status_commands_total{instance=\"$host\"}[$interval])>0) or topk(5, irate(mysql_global_status_commands_total{instance=\"$host\"}[5m])>0)",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    },
    {
     "title": "$host - MySQL Client Thread Activity",
     "type": "graph",
     "description": "**MySQL Active Threads**\n\nThreads Connected is the number of open connections, while Threads Running is the number of threads not sleeping.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
     "repeat": "host",
     "yaxes": [
      { "format": "short", "label": "Threads" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_connected{instance=\"$host\"}[5m])",
       "legendFormat": "Peak Threads Connected"
      },
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or\nmax_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
       "legendFormat": "Peak Threads Running"
      },
      {
       "expr": "avg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[$interval]) or \navg_over_time(mysql_global_status_threads_running{instance=\"$host\"}[5m])",
       "legendFormat": "Avg Threads Running"
      }
     ]
    }
   ]
  },
  {
   "title": "MySQL - Group Replication, M/S Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Member Statistics",
     "type": "graph",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 10 },
     "repeat": "host",
     "yaxes": [
      { "format": "Bps", "label": "bits out (-) / bits in (+)" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_CHECKED{instance=\"$host\"}",
       "legendFormat": "Tx Checked"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_CONFLICTS_DETECTED{instance=\"$host\"}",
       "legendFormat": "Conflicts Detected"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_IN_QUEUE{instance=\"$host\"}",
       "legendFormat": "Tx In Queue"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_LOCAL_PROPOSED{instance=\"$host\"}",
       "legendFormat": "Tx Local Porposed"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_LOCAL_ROLLBACK{instance=\"$host\"}",
       "legendFormat": "Tx Local Rollback"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_REMOTE_APPLIED{instance=\"$host\"}",
       "legendFormat": "Tx Remote Applied"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_REMOTE_IN_APPLIER_QUEUE{instance=\"$host\"}",
       "legendFormat": "Tx Remote in Applier Queue"
      },
      {
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_TRANSACTIONS_ROWS_VALIDATING{instance=\"$host\"}",
       "legendFormat": "Tx Rows Validating"
      }
     ]
    },
    {
     "title": "$host - Member ID",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 22 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Channel Status",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 24 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_group_members_STATUS{MEMBER_HOST=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Role",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_group_members_ROLE{MEMBER_HOST=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Applier State",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_replication_connection_status_STATE{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Transactions Committed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 30 },
     "repeat": "host",
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "mysql_performance_schema_group_replication_group_member_stats_COUNT_CONFLICTS_DETECTED{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - MySQL Replication Delay",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_slave_status_seconds_behind_master{instance=\"$host\"}",
       "legendFormat": "Lag"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU - Load, Usage, Context Switching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$host\"} ",
       "legendFormat": "LoadAvg 1m"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"$host\"})",
       "legendFormat": "VCPUs"
      }
     ]
    },
    {
     "title": "$host - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$host\"} ",
       "legendFormat": "LoadAvg 1m"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"$host\"})",
       "legendFormat": "VCPUs"
      }
     ]
    },
    {
     "title": "$host - Load Average",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "node_load1{instance=~\"$host\"} ",
       "legendFormat": "LoadAvg 1m"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"$host\"})",
       "legendFormat": "VCPUs"
      }
     ]
    },
    {
     "title": "$host - CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "repeat": "host",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "$host - CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "$host - CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "clamp_max((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) )),1)",
       "legendFormat": "{{mode}}"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max Core Utilization"
      }
     ]
    },
    {
     "title": "$host - Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "(rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])) / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
       "legendFormat": "Context Switches per Virtual CPU"
      }
     ]
    },
    {
     "title": "$host - Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "(rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])) / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
       "legendFormat": "Context Switches per Virtual CPU"
      }
     ]
    },
    {
     "title": "$host - Context Switches",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])",
       "legendFormat": "Context Switches"
      },
      {
       "expr": "(rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])) / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
       "legendFormat": "Context Switches per Virtual CPU"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory - Total, Usage, Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - RAM",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 53 },
     "repeat": "host",
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=\"$host\"}"
      }
     ]
    },
    {
     "title": "$host - Memory  Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes", "label": "GB" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{instance=\"$host\"} - (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "node_memory_MemFree{instance=\"$host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Buffers{instance=\"$host\"}",
       "legendFormat": "Buffers"
      },
      {
       "expr": "node_memory_Cached{instance=\"$host\"}",
       "legendFormat": "Cached"
      }
     ]
    },
    {
     "title": "$host - Swap Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapTotal{instance=\"$host\"} - node_memory_SwapFree{instance=\"$host\"}",
       "legendFormat": "Used"
      },
      {
       "calculatedInterval": "2s",
       "expr": "node_memory_SwapFree{instance=\"$host\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_SwapTotal{instance=~\"$host\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "$host - Swap Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
     "repeat": "host",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk - Free Space, IO, Latency, Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "$host - Mountpoint Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
     "repeat": "host",
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "1 - node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} / node_filesystem_size{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$host - Free Space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_filesystem_free{instance=\"$host\", fstype!~\"rootfs|selinuxfs|autofs|rpc_pipefs|tmpfs\"} ",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "$host - I/O Activity",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
     "repeat": "host",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
       "legendFormat": "Page In"
      },
      {
       "calculatedInterval": "2s",
       "expr": "rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024",
       "legendFormat": "Page Out"
      }
     ]
    },
    {
     "title": "$host - Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 75 },
     "repeat": "host",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_reads_completed{instance=~'$host'}[$interval]) or irate(node_disk_reads_completed{instance=~'$host'}[5m])",
       "legendFormat": "Reads: {{device}}"
      },
      {
       "expr": "rate(node_disk_writes_completed{instance=~'$host'}[$interval]) or irate(node_disk_writes_completed{instance=~'$host'}[5m])",
       "legendFormat": "Writes: {{device}}"
      }
     ]
    },
    {
     "title": "$host - Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
     "repeat": "host",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval]) / \nrate(node_disk_reads_completed{instance=~\"$host\"}[$interval])) or \n(irate(node_disk_read_time_ms{instance=~\"$host\"}[5m]) / \nirate(node_disk_reads_completed{instance=~\"$host\"}[5m]))\nor avg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[$interval]) or \navg_over_time(aws_rds_read_latency_average{instance=~\"$host\"}[5m])",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "(rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval]) / \nrate(node_disk_writes_completed{instance=~\"$host\"}[$interval])) or \n(irate(node_disk_write_time_ms{instance=~\"$host\"}[5m]) / \nirate(node_disk_writes_completed{instance=~\"$host\"}[5m]))\nor (avg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[$interval]) or \navg_over_time(aws_rds_write_latency_average{instance=~\"$host\"}[5m]))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "$host - Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 89 },
     "repeat": "host",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_disk_read_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_read_time_ms{instance=~\"$host\"}[5m])/1000",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(node_disk_write_time_ms{instance=~\"$host\"}[$interval])/1000 or \nirate(node_disk_write_time_ms{instance=~\"$host\"}[5m])/1000",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Traffic, Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "repeat": "host",
     "yaxes": [
      { "format": "Bps", "label": "bits out (-) / bits in (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
       "legendFormat": "Inbound"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    },
    {
     "title": "Network Utilization Hourly",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(increase(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))",
       "legendFormat": "Received"
      },
      {
       "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[1h]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  }
 ]
}