{
 "title": "ProxySQL Instance Summary - 2020-04",
 "description": "Updates from April work by michaelc",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "proxysql",
    "label": "ProxySQL Instance",
    "query": "label_values(proxysql_mysql_status_active_transactions, node_name)"
   },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "label_values(proxysql_connection_pool_status{node_name=\"$proxysql\"}, hostgroup)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hostgroup $hostgroup Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }
  },
  {
   "title": "Active Backend Connections for Hostgroup $hostgroup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Number of Backend Connections" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or\nmax_over_time(proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]) ",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Free vs Used Connection Pool States for Hostgroup $hostgroup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(proxysql_connection_pool_conn_free{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or max_over_time(proxysql_connection_pool_conn_free{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "free - {{ endpoint }}"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or max_over_time(proxysql_connection_pool_conn_used{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "used - {{ endpoint }}"
    }
   ]
  },
  { "title": "Hostgroup $hostgroup Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Hostgroup $hostgroup Queries Routed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_connection_pool_queries{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_queries{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Latency for Hostgroup $hostgroup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "max_over_time(proxysql_connection_pool_latency_us{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or \nmax_over_time(proxysql_connection_pool_latency_us{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Hostgroup $hostgroup Membership",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Hostgroup $hostgroup Members Count",
     "type": "graph",
     "gridPos": { "h": 3, "w": 20, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "scalar(count(proxysql_connection_pool_status{node_name=\"$proxysql\", hostgroup=\"$hostgroup\"}))",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "Thread Workers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "proxysql_mysql_status_mysql_thread_workers{node_name=\"$proxysql\"}",
       "legendFormat": "Size"
      }
     ]
    },
    {
     "title": "Endpoint Status",
     "type": "table",
     "description": "Status number to state mapping:\n\n1 `ONLINE`\n2 `SHUNNED`\n3 `OFFLINE_SOFT`\n4 `OFFLINE_HARD`\n\nFor status details, see the [description](https://github.com/sysown/proxysql/blob/master/doc/admin_tables.md#mysql_servers).",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "proxysql_connection_pool_status{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
       "legendFormat": "{{ endpoint }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Client Connections (All Host Groups)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}[$interval]) or \nmax_over_time(proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend Client Connections"
      },
      {
       "calculatedInterval": "2m",
       "expr": "rate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[$interval]) or \nirate(proxysql_mysql_status_questions{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Questions Rate"
      }
     ]
    },
    {
     "title": "Failed Backend Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (node_name,endpoint) (rate(proxysql_connection_pool_conn_err{node_name=\"proxysql1\", hostgroup=~\"2000\"}[5m]) or irate(proxysql_connection_pool_conn_err{node_name=\"proxysql1\", hostgroup=~\"2000\"}[5m]))",
       "legendFormat": "{{ endpoint }}"
      }
     ]
    },
    {
     "title": "Active Frontend Host Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "max_over_time(proxysql_processlist_client_connection_list{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_processlist_client_connection_list{node_name=\"$proxysql\"}[5m]) ",
       "legendFormat": "{{ client_host }}"
      }
     ]
    },
    {
     "title": "MySQL Status COM Counters",
     "type": "graph",
     "description": "All the COM counters exposed as of 2020-04-07",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_com_backend_stmt_execute{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_backend_stmt_execute{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend - Statement Execute"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_backend_stmt_close{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_backend_stmt_close{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend - Statement Close"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_backend_stmt_prepare{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_backend_stmt_prepare{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend - Statement Prepare"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_autocommit{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_autocommit{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Auto-Commit"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_autocommit_filtered{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_autocommit_filtered{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Auto-Commit Filtered"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_backend_change_user{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_backend_change_user{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend - Change User"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_backend_init_db{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_backend_init_db{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend - Init DB"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_backend_set_names{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_backend_set_names{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend - Set Names"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_commit{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_commit{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Commit"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_commit_filtered{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_commit_filtered{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Commit Filtered"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_frontend_init_db{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_frontend_init_db{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend - Init DB"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_frontend_stmt_close{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_frontend_stmt_close{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend - Statement Close"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_frontend_set_names{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_frontend_set_names{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend - Set Names"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_frontend_use_db{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_frontend_use_db{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend - Use DB"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_rollback{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_rollback{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Rollback"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_rollback_filtered{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_rollback_filtered{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Rollback Filtered"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_frontend_stmt_execute{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_frontend_stmt_execute{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend - Statement Execute"
      },
      {
       "expr": "rate(proxysql_mysql_status_com_frontend_stmt_prepare{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_com_frontend_stmt_prepare{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend - Statement Prepare"
      }
     ]
    },
    {
     "title": "Client Connection Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_client_connections_aborted{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_client_connections_aborted{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Connections Aborted"
      },
      {
       "expr": "rate(proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_client_connections_connected{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Connections Connected"
      },
      {
       "expr": "rate(proxysql_mysql_status_client_connections_created{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_client_connections_created{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Connections Created"
      },
      {
       "expr": "rate(proxysql_mysql_status_client_connections_hostgroup_locked{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status__client_connections_hostgroup_locked{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Connections Hostgroup Locked"
      },
      {
       "expr": "rate(proxysql_mysql_status_client_connections_non_idle{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_client_connections_non_idle{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Connections Non-Idle"
      }
     ]
    },
    {
     "title": "Access Denied Conditions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_access_denied_max_connections{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_access_denied_max_connections{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Max Connections"
      },
      {
       "expr": "rate(proxysql_mysql_status_access_denied_max_user_connections{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_access_denied_max_user_connections{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Max User Connections"
      },
      {
       "expr": "rate(proxysql_mysql_status_access_denied_wrong_password{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_access_denied_wrong_password{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Wrong Password"
      }
     ]
    },
    {
     "title": "Connection Pool GET States",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_connpool_get_conn_failure{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_connpool_get_conn_failure{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Failure"
      },
      {
       "expr": "rate(proxysql_mysql_status_connpool_get_conn_immediate{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_connpool_get_conn_immediate{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Immediate"
      },
      {
       "expr": "rate(proxysql_mysql_status_connpool_get_conn_latency_awareness{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_connpool_get_conn_latency_awareness{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Latency Awareness"
      },
      {
       "expr": "rate(proxysql_mysql_status_connpool_get_conn_success{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_connpool_get_conn_success{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Success"
      }
     ]
    },
    {
     "title": "Queries Frontend and Backend Bytes sent/received",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_queries_frontends_bytes_recv{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_queries_frontends_bytes_recv{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend Bytes Received"
      },
      {
       "expr": "rate(proxysql_mysql_status_queries_frontends_bytes_sent{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_queries_frontends_bytes_sent{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Frontend Bytes Sent"
      },
      {
       "expr": "rate(proxysql_mysql_status_queries_backends_bytes_sent{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_queries_backends_bytes_sent{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend Bytes Sent"
      },
      {
       "expr": "rate(proxysql_mysql_status_queries_backends_bytes_recv{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_queries_backends_bytes_recv{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend Bytes Received"
      },
      {
       "expr": "rate(proxysql_mysql_status_queries_with_max_lag_ms{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_queries_with_max_lag_ms{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Max Lag ms"
      }
     ]
    },
    {
     "title": "MySQL Status Statements",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_stmt_cached{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_stmt_cached{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Cached"
      },
      {
       "expr": "rate(proxysql_mysql_status_stmt_client_active_total{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_stmt_client_active_total{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Active Total"
      },
      {
       "expr": "rate(proxysql_mysql_status_stmt_client_active_unique{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_stmt_client_active_unique{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Client Active Unique"
      },
      {
       "expr": "rate(proxysql_mysql_status_stmt_max_stmt_id{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_stmt_max_stmt_id{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Max Statement ID"
      },
      {
       "expr": "rate(proxysql_mysql_status_stmt_server_active_total{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_stmt_server_active_total{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Server Active Total"
      },
      {
       "expr": "rate(proxysql_mysql_status_stmt_server_active_unique{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_stmt_server_active_unique{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Server Active Unique"
      }
     ]
    },
    {
     "title": "MySQL Killed & Unexpected",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(proxysql_mysql_status_mysql_killed_backend_connections{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_mysql_killed_backend_connections{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend Killed Connections"
      },
      {
       "expr": "rate(proxysql_mysql_status_mysql_killed_backend_queries{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_mysql_killed_backend_queries{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend Killed Queries"
      },
      {
       "expr": "rate(proxysql_mysql_status_mysql_unexpected_frontend_packets{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_mysql_unexpected_frontend_packets{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend Killed Queries"
      },
      {
       "expr": "rate(proxysql_mysql_status_mysql_unexpected_frontend_com_quit{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_mysql_unexpected_frontend_com_quit{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Backend Killed Queries"
      }
     ]
    }
   ]
  },
  {
   "title": "Query Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Cache Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "bytes", "label": "QC Total Memory Used" }
     ],
     "targets": [
      {
       "expr": "max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "QC Total Memory used"
      },
      {
       "expr": "(max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}[5m]))/\n(max_over_time(proxysql_mysql_status_query_cache_entries{node_name=\"$proxysql\"}[$interval]) or\nmax_over_time(proxysql_mysql_status_query_cache_entries{node_name=\"$proxysql\"}[5m]))",
       "legendFormat": "Bytes for cached query avg"
      },
      {
       "expr": "rate(proxysql_mysql_status_query_cache_purged{node_name=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_query_cache_purged{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "QC Purged"
      }
     ]
    },
    {
     "title": "Query Cache Efficiency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "((rate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get_ok{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get{node_name=\"$proxysql\"}[5m])))        ",
       "legendFormat": "Query Cache GET efficiency"
      },
      {
       "expr": "((rate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_out{node_name=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_in{node_name=\"$proxysql\"}[5m])))        ",
       "legendFormat": "Insert VS read efficiency (high is good)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Traffic and Mirroring Efficiency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "(rate(proxysql_connection_pool_bytes_data_recv{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) + rate(proxysql_connection_pool_bytes_data_sent{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval])) or (irate(proxysql_connection_pool_bytes_data_recv{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]) + irate(proxysql_connection_pool_bytes_data_sent{node_name=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
       "legendFormat": "{{ endpoint }}"
      }
     ]
    },
    {
     "title": "Mirroring Efficiency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(proxysql_mysql_status_mirror_concurrency{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_mysql_status_mirror_concurrency{node_name=\"$proxysql\"}[5m]) ",
       "legendFormat": "Concurrent Mirror threads"
      },
      {
       "expr": "max_over_time(proxysql_mysql_status_mirror_queue_length{node_name=\"$proxysql\"}[$interval]) or \nmax_over_time(proxysql_mysql_status_mirror_queue_length{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Mirror queue length (queries)"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "proxysql_mysql_status_query_cache_memory_bytes{node_name=\"$proxysql\"}",
       "legendFormat": "Query Cache"
      },
      {
       "expr": "proxysql_mysql_status_sqlite3_memory_bytes{node_name=\"$proxysql\"}",
       "legendFormat": "SQLite"
      },
      {
       "expr": "proxysql_mysql_status_connpool_memory_bytes{node_name=\"$proxysql\"}",
       "legendFormat": "Connection Pool"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "max_over_time(proxysql_stats_memory_auth_memory{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_auth_memory{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Used by the Authentication module"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_jemalloc_active{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_active{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Allocated in pages by the Application"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_jemalloc_allocated{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_allocated{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Allocated by the Application"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_jemalloc_mapped{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_mapped{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Extents mapped by the Allocator"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_jemalloc_metadata{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_metadata{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Dedicated to Metadata"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_jemalloc_resident{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_resident{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Physically Resident Data pages Mapped by the Allocator"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_jemalloc_retained{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_jemalloc_retained{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Retained Memory"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_query_digest_memory{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_query_digest_memory{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Memory Used to Store Data"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_sqlite3_memory_bytes{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_sqlite3_memory_bytes{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Used by the Embedded SQLite"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_stack_memory_mysql_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_mysql_threads{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Stack Memory for Mysql Threads"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_stack_memory_admin_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_admin_threads{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Stack Memory for Admin Threads"
      },
      {
       "expr": "max_over_time(proxysql_stats_memory_stack_memory_cluster_threads{node_name=\"$proxysql\"}[$interval]) or max_over_time(proxysql_stats_memory_stack_memory_cluster_threads{node_name=\"$proxysql\"}[5m])",
       "legendFormat": "Stack Memory for Cluster Threads"
      }
     ]
    }
   ]
  }
 ]
}