{
 "title": "ProxySQL Query Cache Digests",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "proxysql",
    "label": "ProxySQL Instance",
    "query": "label_values(proxysql_mysql_status_active_transactions, node_name)"
   },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "label_values(proxysql_connection_pool_status{node_name=\"$proxysql\"}, hostgroup)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, cluster)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "schemaname",
    "label": "Schema Name",
    "query": "label_values(proxysql_query_digest_query_count{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\"}, schemaname)"
   },
   {
    "name": "username",
    "label": "Client Username",
    "query": "label_values(proxysql_query_digest_query_count{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\"},username)"
   },
   {
    "name": "digest",
    "label": "Query Digest",
    "query": "label_values(proxysql_query_digest_query_count{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\"},digest)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Query Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxysql_query_digest_query_count{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\",schemaname=~\"$schemaname\",username=~\"$username\"}[5m])",
     "legendFormat": "{{ node_name }}.{{ hostgroup }}.{{ schemaname }}.{{username }}.{{ digested_text }}"
    }
   ]
  },
  {
   "title": "Query Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxysql_query_digest_query_time_sum{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\",schemaname=~\"$schemaname\",username=~\"$username\"}[5m])",
     "legendFormat": "{{ node_name }}.{{ hostgroup }}.{{ schemaname }}.{{username }}.{{ digest }}"
    }
   ]
  },
  {
   "title": "Query Time Max",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxysql_query_digest_query_time_max{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\",schemaname=~\"$schemaname\",username=~\"$username\"}[5m])",
     "legendFormat": "{{ node_name }}.{{ hostgroup }}.{{ schemaname }}.{{username }}.{{ digest }}"
    }
   ]
  },
  {
   "title": "Query Time Min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxysql_query_digest_query_time_min{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\",schemaname=~\"$schemaname\",username=~\"$username\"}[5m])",
     "legendFormat": "{{ node_name }}.{{ hostgroup }}.{{ schemaname }}.{{username }}.{{ digest }}"
    }
   ]
  },
  {
   "title": "Query Rows Affected",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxysql_query_digest_rows_affected_sum{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\",schemaname=~\"$schemaname\",username=~\"$username\"}[5m])",
     "legendFormat": "{{ node_name }}.{{ hostgroup }}.{{ schemaname }}.{{username }}.{{ digest }}"
    }
   ]
  },
  {
   "title": "Query Rows Sent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(proxysql_query_digest_rows_sent_sum{node_name=\"$proxysql\",hostgroup=~\"$hostgroup\",schemaname=~\"$schemaname\",username=~\"$username\"}[5m])",
     "legendFormat": "{{ node_name }}.{{ hostgroup }}.{{ schemaname }}.{{username }}.{{ digest }}"
    }
   ]
  }
 ]
}